global:
  scrape_interval: 15s  # Intervalle de scrapping

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.33.10:8080']

  - job_name: 'app-spring'
    metrics_path: '/gestion-station-ski/actuator/prometheus'  # Chemin pour les métriques Spring
    static_configs:
      - targets: ['app-spring:8082']  # Utilisez le nom du service défini dans docker-compose

