version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD= # Laissez vide si vous n'utilisez pas de mot de passe
      - MYSQL_DATABASE=ski-project3
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-spring:
    depends_on:
      - mysqldb
    image: nawel119/gestion-station-ski:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/ski-project3?createDatabaseIfNotExist=true", 
        "spring.datasource.username": "root",
        "spring.datasource.password": "",  
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.database-platform": "org.hibernate.dialect.MySQL5Dialect"
      }'
    stdin_open: true
    tty: true

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  db:
  prometheus_data:
