version: "2.29.7"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-spring:
    depends_on:
      - mysqldb
    image: ghadaimg/tp-foyer:latest
    #build : ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.servlet.context-path": "/tpfoyer",
        "server.port": "8089",
        "spring.datasource.url"  : "jdbc:mysql://192.168.50.4:3306/tpfoyer_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "management.endpoint.prometheus.enabled": "true",
        "management.endpoints.web.exposure.include": "prometheus"
      }'
    stdin_open: true
    tty: true

volumes:
  db :