
global:
  scrape_interval: 15s  
rule_files:


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.33.10:8080']

  - job_name: 'app-spring'
    metrics_path: '/gestion-station-ski/actuator/prometheus'
    static_configs:
      - targets: ['5nids-g1-projetdevops-job-pipeline-app-spring-1:8082']  
